name: 'Branch Preview'
description: 'Preview Fastly Service'

runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v3
      # Download Yarn and the Fastly CLI and install the project dependencies
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cli_version: '10.2.0'
      - run: yarn
        shell: bash

      # Create a new Fastly Service name with the PR number appended
      - name: Set service-name
        id: service-name
        run: echo "SERVICE_NAME=$(yq '.name' fastly.toml)-${{ github.event.number }}" >> "$GITHUB_OUTPUT"
        shell: bash

      # Delete the Fastly Service
      - if: github.event.action == closed
        run: fastly service delete --quiet --service-name ${{ steps.service-name.outputs.SERVICE_NAME }} --force --token ${{ secrets.FASTLY_API_KEY }} || true
        shell: bash

      # Add the service name to fastly.toml so that the Fstly CLI is aware of the new name
      - if: github.event.action != closed
        run: sed -i 's/^name = ".*"/name = "${{ steps.service-name.outputs.SERVICE_NAME }}"/g' fastly.toml
        shell: bash
      # Deploy to Fastly and let Fastly choose a subdomain of edgecompute.app to attach to the service
      - if: github.event.action != closed
        run: |
          if fastly service describe --quiet --service-name="${{ steps.service-name.outputs.SERVICE_NAME }}" --token ${{ secrets.FASTLY_API_KEY }} ; then
            FASTLY_SERVICE_ID="$(fastly service describe --service-name="${{ steps.service-name.outputs.SERVICE_NAME }}" --token ${{ secrets.FASTLY_API_KEY }} --quiet --json | jq -r '.ID')" fastly compute publish --verbose --token ${{ secrets.FASTLY_API_KEY }}
          else
            fastly compute publish --verbose -i --token ${{ secrets.FASTLY_API_KEY }}
          fi
        shell: bash
      # Retrieve the newly created domain for the service and add it to the pull-request summary
      - if: github.event.action != closed
        run: fastly domain list --quiet --version latest --json --service-name="${{ steps.service-name.outputs.SERVICE_NAME }}" --token ${{ secrets.FASTLY_API_KEY }} | jq -r '.[0].Name'
        shell: bash

      - if: github.event.action != closed
        name: Set domain
        shell: bash
        id: domain
        run: echo "DOMAIN=$(fastly domain list --quiet --version latest --json --service-name="${{ steps.service-name.outputs.SERVICE_NAME }}" --token ${{ secrets.FASTLY_API_KEY }} | jq -r '.[0].Name')" >> "$GITHUB_OUTPUT"


      - if: github.event.action != closed
        shell: bash
        name: Add domain to summary
        run: echo 'This pull-request has been deployed to Fastly and is available at <https://${{ steps.domain.outputs.DOMAIN }}> 🚀' >> $GITHUB_STEP_SUMMARY

      # Run our integration tests against the newly deployed service
      - if: github.event.action != closed
        shell: bash
        run: npm run test:integration
        env:
          HOST: "https://${{ steps.domain.outputs.DOMAIN }}"
