name: Deploy to new Fastly Compute Service and test
concurrency: dev_environment
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/preview
        with:
          fastly-api-token: ${{ secrets.FASTLY_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
